In [1]:
%matplotlib notebook

In [2]:
# Dependencies
import matplotlib.pyplot as plt
from matplotlib.legend_handler import HandlerLine2D
import requests
import pandas as pd
from config import api_key
import json
import pandas as pd
import glob
import numpy as np

### 1) API: Requests URL & Create CSV File

#### API: American Community Survey 1-Year Data (2005-2019) - State Level

In [3]:
# Create csv file for individual year from 2009 to 2019

# Means of Transportation
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_001E'
title = 'transportation'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'..\Resources_api\{year}_{title}.csv')

In [4]:
# Worked From Home
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_049E'
title = 'worked_fm_home'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

In [5]:
# Drove Alone
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_009E'
title = 'drove'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

In [6]:
# Carpooled
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_017E'
title = 'carpooled'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

In [7]:
# Walked
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_033E'
title = 'walked'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

In [8]:
# Public Transportation (Excluding Taxi)
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_025E'
title = 'public_transportation'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

In [9]:
# Taxi, Motercycle, Bicycle
years = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
variable = 'B08101_041E'
title = 'taxi_bikes'

for year in years:
    url = f'https://api.census.gov/data/{year}/acs/acs1?get=NAME,{variable}&for=state:*&key={api_key}'
    data = requests.get(url).json()
    col_name = ['state', year, 'state code']
    df = pd.DataFrame(data[1:], columns=col_name)
    clean_df = df.drop(columns=['state code'])
    clean_df.to_csv(f'{year}_{title}.csv')

### 2) Read CSV Files

In [10]:
# Toal Means of Transportation
df = pd.read_csv('2009_transportation.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2010_transportation.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2011_transportation.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2012_transportation.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2013_transportation.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2014_transportation.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2015_transportation.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2016_transportation.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2017_transportation.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2018_transportation.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2019_transportation.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
transportation_dfs = pd.concat(dfs, axis=1)
transportation_df = transportation_dfs.rename(columns={'index':'state'})

In [11]:
# Worked From Home
df = pd.read_csv('2009_worked_fm_home.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2010_worked_fm_home.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2011_worked_fm_home.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2012_worked_fm_home.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2013_worked_fm_home.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2014_worked_fm_home.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2015_worked_fm_home.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2016_worked_fm_home.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2017_worked_fm_home.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2018_worked_fm_home.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv('2019_worked_fm_home.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
worked_fm_home_dfs = pd.concat(dfs, axis=1)
worked_fm_home_df = worked_fm_home_dfs.rename(columns={'index':'state'})

In [12]:
# Drove
title = 'drove'

df = pd.read_csv(f'2009_{title}.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2010_{title}.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2011_{title}.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2012_{title}.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2013_{title}.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2014_{title}.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2015_{title}.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2016_{title}.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2017_{title}.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2018_{title}.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2019_{title}.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
drove_dfs = pd.concat(dfs, axis=1)
drove_df = drove_dfs.rename(columns={'index':'state'})

In [13]:
# Carpooled
title = 'carpooled'

df = pd.read_csv(f'2009_{title}.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2010_{title}.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2011_{title}.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2012_{title}.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2013_{title}.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2014_{title}.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2015_{title}.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2016_{title}.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2017_{title}.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2018_{title}.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2019_{title}.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
carpooled_dfs = pd.concat(dfs, axis=1)
carpooled_df = carpooled_dfs.rename(columns={'index':'state'})

In [14]:
# Walked
title = 'walked'

df = pd.read_csv(f'2009_{title}.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2010_{title}.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2011_{title}.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2012_{title}.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2013_{title}.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2014_{title}.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2015_{title}.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2016_{title}.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2017_{title}.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2018_{title}.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2019_{title}.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
walked_dfs = pd.concat(dfs, axis=1)
walked_df = walked_dfs.rename(columns={'index':'state'})

In [15]:
# Public Transportation
title = 'public_transportation'

df = pd.read_csv(f'2009_{title}.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2010_{title}.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2011_{title}.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2012_{title}.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2013_{title}.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2014_{title}.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2015_{title}.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2016_{title}.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2017_{title}.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2018_{title}.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2019_{title}.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
public_transportation_dfs = pd.concat(dfs, axis=1)
public_transportation_df = public_transportation_dfs.rename(columns={'index':'state'})

In [16]:
# Taxi Bikes
title = 'taxi_bikes'

df = pd.read_csv(f'2009_{title}.csv')
df_2009 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2010_{title}.csv')
df_2010 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2011_{title}.csv')
df_2011 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2012_{title}.csv')
df_2012 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2013_{title}.csv')
df_2013 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2014_{title}.csv')
df_2014 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2015_{title}.csv')
df_2015 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2016_{title}.csv')
df_2016 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2017_{title}.csv')
df_2017 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2018_{title}.csv')
df_2018 = df.drop(columns=['Unnamed: 0'])

df = pd.read_csv(f'2019_{title}.csv')
df_2019 = df.drop(columns=['Unnamed: 0'])

dfs = [df.set_index(['state']) for df in [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019]]
taxi_bikes_dfs = pd.concat(dfs, axis=1)
taxi_bikes_df = taxi_bikes_dfs.rename(columns={'index':'state'})

### 3) Create DataFrame

#### 3.1) DMV Means of Transporation Individual DataFrames

In [17]:
# DMV Total Means of Transportation
#transportation_df
va_transportation = pd.DataFrame(transportation_df.loc['Virginia']).rename(columns={'Virginia':'VA Total'})
dc_transportation = pd.DataFrame(transportation_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Total'})
md_transportation = pd.DataFrame(transportation_df.loc['Maryland']).rename(columns={'Maryland':'MD Total'})
dmv_total = pd.concat([va_transportation, dc_transportation, md_transportation], axis=1)
dmv_total.head()

      VA Total  DC Total  MD Total
2009   3822714    291083   2840465
2010   3845626    296717   2847946
2011   3883249    306801   2855500
2012   3967188    326143   2909794
2013   4018400    330087   2946590

In [18]:
# DMV Worked From Home
# worked_fm_home_df
va_worked_fm_home = pd.DataFrame(worked_fm_home_df.loc['Virginia']).rename(columns={'Virginia':'VA fm Home'})
dc_worked_fm_home = pd.DataFrame(worked_fm_home_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC fm Home'})
md_worked_fm_home = pd.DataFrame(worked_fm_home_df.loc['Maryland']).rename(columns={'Maryland':'MD fm Home'})
dmv_worked_fm_home = pd.concat([va_worked_fm_home, dc_worked_fm_home, md_worked_fm_home], axis=1)
dmv_worked_fm_home.head()

      VA fm Home  DC fm Home  MD fm Home
2009      157174       15041      117152
2010      167035       14870      122635
2011      176921       14700      116524
2012      187750       15129      121882
2013      182279       14474      124944

In [19]:
# DMV Drove
# drove_df
va_drove = pd.DataFrame(drove_df.loc['Virginia']).rename(columns={'Virginia':'VA Drove'})
dc_drove = pd.DataFrame(drove_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Drove'})
md_drove = pd.DataFrame(drove_df.loc['Maryland']).rename(columns={'Maryland':'MD Drove'})
dmv_drove = pd.concat([va_drove, dc_drove, md_drove], axis=1)
dmv_drove.head()

      VA Drove  DC Drove  MD Drove
2009   2962941    106115   2084261
2010   2966482    103239   2079711
2011   3032187    101621   2091777
2012   3067222    111088   2135379
2013   3112188    106657   2180872

In [20]:
# DMV Carpooled
# carpooled_df
va_carpooled = pd.DataFrame(carpooled_df.loc['Virginia']).rename(columns={'Virginia':'VA Carpooled'})
dc_carpooled = pd.DataFrame(carpooled_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Carpooled'})
md_carpooled = pd.DataFrame(carpooled_df.loc['Maryland']).rename(columns={'Maryland':'MD Carpooled'})
dmv_carpooled = pd.concat([va_carpooled, dc_carpooled, md_carpooled], axis=1)
dmv_carpooled.head()

      VA Carpooled  DC Carpooled  MD Carpooled
2009        396824         19375        284342
2010        383909         17630        304131
2011        355426         19792        288690
2012        393282         18396        286359
2013        376679         17512        266301

In [21]:
# DMV Walked
# walked_df
va_walked = pd.DataFrame(walked_df.loc['Virginia']).rename(columns={'Virginia':'VA Walked'})
dc_walked = pd.DataFrame(walked_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Walked'})
md_walked = pd.DataFrame(walked_df.loc['Maryland']).rename(columns={'Maryland':'MD Walked'})
dmv_walked = pd.concat([va_walked, dc_walked, md_walked], axis=1)
dmv_walked.head()

      VA Walked  DC Walked  MD Walked
2009      85818      32328      74434
2010     103982      34895      64917
2011      90716      36200      65220
2012      87938      38795      71970
2013      99433      45003      69897

In [22]:
# DMV Public Transportation
# public_transportation_df
va_public_transportation = pd.DataFrame(public_transportation_df.loc['Virginia']).rename(columns={'Virginia':'VA Public Transportation'})
dc_public_transportation = pd.DataFrame(public_transportation_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Public Transportation'})
md_public_transportation = pd.DataFrame(public_transportation_df.loc['Maryland']).rename(columns={'Maryland':'MD Public Transportation'})
dmv_public_transportation = pd.concat([va_public_transportation, dc_public_transportation, md_public_transportation], axis=1)
dmv_public_transportation.head()

,VA Public Transportation,DC Public Transportation,MD Public Transportation
2009,168359,108046,248834
2010,168554,113648,245628
2011,174888,121460,262605
2012,174525,125890,258280
2013,176996,127045,268560

In [23]:
# DMV Taxi and Bikes
# taxi_bikes_df 
dmv_taxi_bikes = pd.DataFrame(taxi_bikes_df.loc[['Virginia','District of Columbia','Maryland']])

va_taxi_bikes = pd.DataFrame(taxi_bikes_df.loc['Virginia']).rename(columns={'Virginia':'VA Taxi/Bikes'})
dc_taxi_bikes = pd.DataFrame(taxi_bikes_df.loc['District of Columbia']).rename(columns={'District of Columbia':'DC Taxi/Bikes'})
md_taxi_bikes = pd.DataFrame(taxi_bikes_df.loc['Maryland']).rename(columns={'Maryland':'MD Taxi/Bikes'})
dmv_taxi_bikes = pd.concat([va_taxi_bikes, dc_taxi_bikes, md_taxi_bikes], axis=1)
dmv_taxi_bikes.head()

      VA Taxi/Bikes  DC Taxi/Bikes  MD Taxi/Bikes
2009          51598          10178          31442
2010          55664          12435          30924
2011          53111          13028          30684
2012          56471          16845          35924
2013          70825          19396          36016

#### 3.2) DMA Area: Expenditure DataFrame

In [24]:
# Read SAEXP1__ALL_AREAS_1997_2019.csv
file = 'Resources\SAEXP1__ALL_AREAS_1997_2019.csv'
data = pd.read_csv(file)
data.head()

data2 = data[['GeoName', 'Description','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']]
data3 = data2.set_index('GeoName')

# VA, MD, DC
va_data = data3.loc['Virginia'].rename(columns={'Description':'VA Description'}).set_index('VA Description')
md_data = data3.loc['Maryland'].rename(columns={'Description':'MD Description'}).set_index('MD Description')
dc_data = data3.loc['District of Columbia'].rename(columns={'Description':'DC Description'}).set_index('DC Description')

# motor_vehicles_and_parts
va_motor = pd.DataFrame(va_data.iloc[3])
md_motor = pd.DataFrame(md_data.iloc[3])
dc_motor = pd.DataFrame(dc_data.iloc[3])

# transportation_services 
va_tservice = pd.DataFrame(va_data.iloc[16])
md_tservice = pd.DataFrame(md_data.iloc[16])
dc_tservice = pd.DataFrame(dc_data.iloc[16])

# Merge: motor_vehicles_and_parts + transportation_services
va_motor_tservice = pd.concat([va_motor, va_tservice], axis=1)
md_motor_tservice = pd.concat([md_motor, md_tservice], axis=1)
dc_motor_tservice = pd.concat([dc_motor, dc_tservice], axis=1)

## 4) Plots and Data Visualization

#### Summaries and Reflecting Questions
1. The expenditure on motor vehicles and parts: More in VA than in MD.
2. Population that used public transporation to work: More in MD than in VA. 


#### Reflectiing Question:
1. How often do people in VA/MD use public transporation?
2. What are the average travelling distance?
3. How do frequency and distance affect expenditures in public transportation?

### Expenditure and Population Comparison: Public Transporation Service (VA/MD)

In [25]:
# Public Transporation
year = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
# Population
va_public_transportation = dmv_public_transportation['VA Public Transportation']
md_public_transportation = dmv_public_transportation['MD Public Transportation']

# Expenditure
va_tservice = pd.DataFrame(va_data.iloc[16])
md_tservice = pd.DataFrame(md_data.iloc[16])

# Plot
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2)
ax1.plot(year, va_public_transportation, color = 'coral', linestyle = '--', label='VA')
ax1.plot(year, md_public_transportation, color = 'steelblue', linestyle = '--', label='MD')

ax2.plot(year, va_tservice, color = 'coral', label='VA')
ax2.plot(year, md_tservice, color = 'steelblue', label='MD')

ax1.legend()
ax1.set_title('Population: PTS')
ax1.set_ylabel('Population')

ax2.legend()
ax2.set_title('Expenditure: PTS')
ax2.set_ylabel('Millions of Dollars')

plt.setp((ax1, ax2), xticks=[0, 5, 10], xticklabels=['2009', '2015', '2019'])

plt.tight_layout()
plt.show()

fig.savefig('Public Transportation.png')

In [26]:
dmv_carpooled
#dmv_carpooled.sum()
dmv_public_transportation
#dmv_public_transportation.sum()

,VA Public Transportation,DC Public Transportation,MD Public Transportation
2009,168359,108046,248834
2010,168554,113648,245628
2011,174888,121460,262605
2012,174525,125890,258280
2013,176996,127045,268560
2014,191066,123707,267211
2015,194457,128135,271533
2016,171640,130451,258950
2017,175257,122643,259404
2018,191112,130216,242247
2019,186834,131786,246926

# Part 3: ...

In [27]:
#locating the csv files...
#year 2009-2019...
carpooled_csv = "Resources/carpool.csv"
drove_csv = "Resources/drove.csv"
publicTrans_csv = "Resources/publicTransit.csv"
taxiBikes_csv = "Resources/taxiBikes.csv"
transport_csv = "Resources/transportation.csv"
walk_csv = "Resources/walked.csv"
wfh_csv = "Resources/wfh.csv"

In [28]:
#reading the csv files...

#year 2009-2019...
carpooled_df = pd.read_csv(carpooled_csv)
drove_df = pd.read_csv(drove_csv)
publicTrans_df = pd.read_csv(publicTrans_csv)
taxiBikes_df = pd.read_csv(taxiBikes_csv)
transport_df = pd.read_csv(transport_csv)
walk_df = pd.read_csv(walk_csv)
wfh_df = pd.read_csv(wfh_csv)

In [29]:
# Merge the first two datasets on "state" so that no data is lost
combined_states_df = pd.merge(carpooled_df, drove_df, how='outer', on='state')
combined_states_df.head()

,state,2009_x,2010_x,2011_x,2012_x,2013_x,2014_x,2015_x,2016_x,2017_x,...,2010_y,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y,2019_y
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,1648706.0,1657419.0,1680837.0,1713067.0,1724178.0,1719972.0,1768180.0,1748949.0,1784690.0,1817479.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,230116.0,237947.0,235946.0,238572.0,249481.0,246577.0,250492.0,243466.0,241624.0,244725.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,2005289.0,2009959.0,2088074.0,2100376.0,2178267.0,2234511.0,2289515.0,2362162.0,2417249.0,2478184.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,1005284.0,1006040.0,1013982.0,1020341.0,1031366.0,1035546.0,1050898.0,1068253.0,1075012.0,1082408.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,11650145.0,11754858.0,12059924.0,12260080.0,12679198.0,13031320.0,13186177.0,13541563.0,13681331.0,13767903.0

In [30]:
# Rename our _x columns to "carpool2009", "carpool2010", "carpool2011", ..."carpool2019"
combined_states_df = combined_states_df.rename(columns={"2009_x":"carpool2009", "2010_x":"carpool2010","2011_x":"carpool2011", "2012_x":"carpool2012","2013_x":"carpool2013","2014_x":"carpool2014", "2015_x":"carpool2015","2016_x":"carpool2016","2017_x":"carpool2017", "2018_x":"carpool2018","2019_x":"carpool2019"})

# Rename our _y columns to "drove2009", "drove2010", "drove2011", ..."drove2019"
combined_states_df = combined_states_df.rename(columns={"2009_y":"drove2009","2010_y":"drove2010","2011_y":"drove2011", "2012_y":"drove2012","2013_y":"drove2013","2014_y":"drove2014", "2015_y":"drove2015","2016_y":"drove2016","2017_y":"drove2017", "2018_y":"drove2018","2019_y":"drove2019"})

combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,drove2010,drove2011,drove2012,drove2013,drove2014,drove2015,drove2016,drove2017,drove2018,drove2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,1648706.0,1657419.0,1680837.0,1713067.0,1724178.0,1719972.0,1768180.0,1748949.0,1784690.0,1817479.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,230116.0,237947.0,235946.0,238572.0,249481.0,246577.0,250492.0,243466.0,241624.0,244725.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,2005289.0,2009959.0,2088074.0,2100376.0,2178267.0,2234511.0,2289515.0,2362162.0,2417249.0,2478184.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,1005284.0,1006040.0,1013982.0,1020341.0,1031366.0,1035546.0,1050898.0,1068253.0,1075012.0,1082408.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,11650145.0,11754858.0,12059924.0,12260080.0,12679198.0,13031320.0,13186177.0,13541563.0,13681331.0,13767903.0

In [31]:
# Merge our newly combined dataframe with the publicTrans_df dataframe
combined_states_df = pd.merge(combined_states_df, publicTrans_df, how="outer", on="state")
combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,7964.0,9329.0,8096.0,9592.0,8276.0,6066.0,6334.0,7234.0,6983.0,8867.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,4034.0,6474.0,5746.0,6589.0,4703.0,5608.0,4381.0,5827.0,4382.0,3373.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,46829.0,52557.0,54614.0,64986.0,57615.0,59686.0,55372.0,55495.0,53718.0,55020.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,6058.0,5271.0,5748.0,5803.0,4072.0,5791.0,4247.0,3788.0,5009.0,5291.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,820349.0,827736.0,851099.0,889921.0,914442.0,923600.0,910353.0,919579.0,914825.0,970901.0

In [32]:
# Rename "2009", "2010", ... "2019" to "public2009", "public2010", ..."public2019"
combined_states_df = combined_states_df.rename(columns={"2009":"public2009","2010":"public2010","2011":"public2011", "2012":"public2012","2013":"public2013","2014":"public2014", "2015":"public2015","2016":"public2016","2017":"public2017", "2018":"public2018","2019":"public2019"})

combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,public2010,public2011,public2012,public2013,public2014,public2015,public2016,public2017,public2018,public2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,7964.0,9329.0,8096.0,9592.0,8276.0,6066.0,6334.0,7234.0,6983.0,8867.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,4034.0,6474.0,5746.0,6589.0,4703.0,5608.0,4381.0,5827.0,4382.0,3373.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,46829.0,52557.0,54614.0,64986.0,57615.0,59686.0,55372.0,55495.0,53718.0,55020.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,6058.0,5271.0,5748.0,5803.0,4072.0,5791.0,4247.0,3788.0,5009.0,5291.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,820349.0,827736.0,851099.0,889921.0,914442.0,923600.0,910353.0,919579.0,914825.0,970901.0

In [33]:
# Merge our newly combined dataframe with the taxiBikes_df dataframe
combined_states_df = pd.merge(combined_states_df, taxiBikes_df, how="outer", on="state")
combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,18172.0,20200.0,20522.0,20809.0,22851.0,19046.0,21175.0,19462.0,19833.0,23984.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,18024.0,17830.0,21165.0,19215.0,19161.0,20256.0,17273.0,18622.0,19454.0,19865.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,61279.0,74987.0,75353.0,77716.0,81828.0,77347.0,74706.0,73568.0,85028.0,83540.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,17820.0,15992.0,12817.0,18200.0,14661.0,16619.0,14882.0,12943.0,16473.0,13591.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,365352.0,380879.0,393237.0,434841.0,449378.0,464283.0,456964.0,455955.0,478550.0,482036.0

In [34]:
# Rename "2009", "2010", ... "2019" to "taxi2009", "taxi2010", ..."taxi2019"
combined_states_df = combined_states_df.rename(columns={"2009":"taxi2009","2010":"taxi2010","2011":"taxi2011", "2012":"taxi2012","2013":"taxi2013","2014":"taxi2014", "2015":"taxi2015","2016":"taxi2016","2017":"taxi2017", "2018":"taxi2018","2019":"taxi2019"})

combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,taxi2010,taxi2011,taxi2012,taxi2013,taxi2014,taxi2015,taxi2016,taxi2017,taxi2018,taxi2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,18172.0,20200.0,20522.0,20809.0,22851.0,19046.0,21175.0,19462.0,19833.0,23984.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,18024.0,17830.0,21165.0,19215.0,19161.0,20256.0,17273.0,18622.0,19454.0,19865.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,61279.0,74987.0,75353.0,77716.0,81828.0,77347.0,74706.0,73568.0,85028.0,83540.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,17820.0,15992.0,12817.0,18200.0,14661.0,16619.0,14882.0,12943.0,16473.0,13591.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,365352.0,380879.0,393237.0,434841.0,449378.0,464283.0,456964.0,455955.0,478550.0,482036.0

In [35]:
# Merge our newly combined dataframe with the transport_df dataframe
combined_states_df = pd.merge(combined_states_df, transport_df, how="outer", on="state")
combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,1951769.0,1953274.0,1970822.0,1983610.0,2007426.0,2011723.0,2053191.0,2041619.0,2068020.0,2134022.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,343424.0,348777.0,356567.0,357776.0,359211.0,363075.0,362804.0,351282.0,355403.0,349811.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,2621839.0,2650164.0,2721795.0,2754451.0,2831592.0,2899727.0,2992943.0,3086150.0,3174586.0,3276420.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,1225968.0,1215837.0,1233150.0,1223214.0,1249674.0,1253288.0,1264585.0,1281666.0,1301150.0,1313514.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,15921475.0,16047067.0,16432358.0,16745843.0,17254926.0,17633846.0,17926224.0,18320629.0,18530052.0,18730251.0

In [36]:
# Rename "2009", "2010", ... "2019" to "transport2009", "transport2010", ..."transport2019"
combined_states_df = combined_states_df.rename(columns={"2009":"transport2009","2010":"transport2010","2011":"transport2011", "2012":"transport2012","2013":"transport2013","2014":"transport2014", "2015":"transport2015","2016":"transport2016","2017":"transport2017", "2018":"transport2018","2019":"transport2019"})

#combined_states_df.head()

In [37]:
# Merge our newly combined dataframe with the walk_df dataframe
combined_states_df = pd.merge(combined_states_df, walk_df, how="outer", on="state")
#combined_states_df.head()

In [38]:
# Rename "2009", "2010", ... "2019" to "walk2009", "walk2010", ..."walk2019"
combined_states_df = combined_states_df.rename(columns={"2009":"walk2009","2010":"walk2010","2011":"walk2011", "2012":"walk2012","2013":"walk2013","2014":"walk2014", "2015":"walk2015","2016":"walk2016","2017":"walk2017", "2018":"walk2018","2019":"walk2019"})

In [39]:
# Merge our newly combined dataframe with the wfh_df dataframe
combined_states_df = pd.merge(combined_states_df, wfh_df, how="outer", on="state")
#combined_states_df.head()

In [40]:
# Rename "2009", "2010", ... "2019" to "WFH2009", "WFH2010", ..."WFH2019"
combined_states_df = combined_states_df.rename(columns={"2009":"WFH2009","2010":"WFH2010","2011":"WFH2011", "2012":"WFH2012","2013":"WFH2013","2014":"WFH2014", "2015":"WFH2015","2016":"WFH2016","2017":"WFH2017", "2018":"WFH2018","2019":"WFH2019"})

combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,WFH2010,WFH2011,WFH2012,WFH2013,WFH2014,WFH2015,WFH2016,WFH2017,WFH2018,WFH2019
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,55782.0,51126.0,50955.0,50055.0,57233.0,63757.0,68581.0,68872.0,71400.0,72440.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,18805.0,16875.0,19899.0,15371.0,13915.0,16095.0,18772.0,15984.0,18738.0,15141.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,150889.0,145782.0,148304.0,150347.0,161653.0,159681.0,189882.0,193915.0,214693.0,248326.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,36259.0,40569.0,42667.0,34589.0,41375.0,38370.0,40509.0,47156.0,48766.0,46196.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,824305.0,857352.0,865162.0,877833.0,930975.0,970039.0,1044550.0,1092887.0,1111955.0,1188387.0

In [41]:
# Replace all NaN values with 0 
combined_states_df = combined_states_df.fillna(0)

In [42]:
# Create a new column called "Total Carpool" and add up each state's numbers per year to fill in the values
combined_states_df["Total Carpool"] = combined_states_df["carpool2009"] + combined_states_df["carpool2010"] + combined_states_df["carpool2011"] + combined_states_df["carpool2012"] + combined_states_df["carpool2013"] + combined_states_df["carpool2014"] + combined_states_df["carpool2015"] + combined_states_df["carpool2016"] + combined_states_df["carpool2017"] + combined_states_df["carpool2018"] + combined_states_df["carpool2019"]

# Create a new column called "Total Drove" and add up each state's numbers per year to fill in the values
combined_states_df["Total Drove"] = combined_states_df["drove2009"] + combined_states_df["drove2010"] + combined_states_df["drove2011"] + combined_states_df["drove2012"] + combined_states_df["drove2013"] + combined_states_df["drove2014"] + combined_states_df["drove2015"] + combined_states_df["drove2016"] + combined_states_df["drove2017"] + combined_states_df["drove2018"] + combined_states_df["drove2019"]

# Create a new column called "Total PublicTransit" and add up each state's numbers per year to fill in the values
combined_states_df["Total PublicTransit"] = combined_states_df["public2009"] + combined_states_df["public2010"] + combined_states_df["public2011"] + combined_states_df["public2012"] + combined_states_df["public2013"] + combined_states_df["public2014"] + combined_states_df["public2015"] + combined_states_df["public2016"] + combined_states_df["public2017"] + combined_states_df["public2018"] + combined_states_df["public2019"]

# Create a new column called "Total taxiBikes" and add up each state's numbers per year to fill in the values
combined_states_df["Total TaxiBikes"] = combined_states_df["taxi2009"] + combined_states_df["taxi2010"] + combined_states_df["taxi2011"] + combined_states_df["taxi2012"] + combined_states_df["taxi2013"] + combined_states_df["taxi2014"] + combined_states_df["taxi2015"] + combined_states_df["taxi2016"] + combined_states_df["taxi2017"] + combined_states_df["taxi2018"] + combined_states_df["taxi2019"]

# Create a new column called "Total Transport" and add up each state's numbers per year to fill in the values
combined_states_df["Total Transport"] = combined_states_df["transport2009"] + combined_states_df["transport2010"] + combined_states_df["transport2011"] + combined_states_df["transport2012"] + combined_states_df["transport2013"] + combined_states_df["transport2014"] + combined_states_df["transport2015"] + combined_states_df["transport2016"] + combined_states_df["transport2017"] + combined_states_df["transport2018"] + combined_states_df["transport2019"]

# Create a new column called "Total Walked" and add up each state's numbers per year to fill in the values
combined_states_df["Total Walked"] = combined_states_df["walk2009"] + combined_states_df["walk2010"] + combined_states_df["walk2011"] + combined_states_df["walk2012"] + combined_states_df["walk2013"] + combined_states_df["walk2014"] + combined_states_df["walk2015"] + combined_states_df["walk2016"] + combined_states_df["walk2017"] + combined_states_df["walk2018"] + combined_states_df["walk2019"]

# Create a new column called "Total WFH" and add up each state's numbers per year to fill in the values
combined_states_df["Total WFH"] = combined_states_df["WFH2009"] + combined_states_df["WFH2010"] + combined_states_df["WFH2011"] + combined_states_df["WFH2012"] + combined_states_df["WFH2013"] + combined_states_df["WFH2014"] + combined_states_df["WFH2015"] + combined_states_df["WFH2016"] + combined_states_df["WFH2017"] + combined_states_df["WFH2018"] + combined_states_df["WFH2019"]


# Create a new column called "Grand Total" and add up the total Carpool, Drove, PublicTransit, TaxiBikes, Transport, Walked, and WFH for each state to fill in the values
combined_states_df["Grand Total"] = combined_states_df["Total Carpool"] + combined_states_df["Total Drove"] + combined_states_df["Total PublicTransit"] + combined_states_df["Total TaxiBikes"] + combined_states_df["Total Transport"] + combined_states_df["Total Walked"] + combined_states_df["Total WFH"]

combined_states_df.head()

,state,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,...,WFH2018,WFH2019,Total Carpool,Total Drove,Total PublicTransit,Total TaxiBikes,Total Transport,Total Walked,Total WFH,Grand Total
0,Alabama,202114.0,195292.0,194044.0,186834.0,169281.0,171927.0,180752.0,165046.0,173508.0,...,71400.0,72440.0,1986540.0,18918279.0,87064.0,226462.0,22135359.0,258387.0,658627.0,44270718.0
1,Alaska,44499.0,45376.0,43244.0,47473.0,46463.0,43221.0,45738.0,44258.0,41554.0,...,18738.0,15141.0,487409.0,2647091.0,55727.0,206018.0,3882686.0,301448.0,184993.0,7765372.0
2,Arizona,325472.0,305162.0,308658.0,300566.0,304044.0,295724.0,307864.0,328645.0,339590.0,...,214693.0,248326.0,3513245.0,24251150.0,612851.0,839876.0,31761872.0,639216.0,1905534.0,63523744.0
3,Arkansas,141904.0,138346.0,125188.0,137885.0,124069.0,136027.0,134929.0,128593.0,126414.0,...,48766.0,46196.0,1469860.0,11380520.0,56207.0,173090.0,13784835.0,246294.0,458864.0,27569670.0
4,California,1873082.0,1831538.0,1780802.0,1821450.0,1825475.0,1813154.0,1770281.0,1846542.0,1837270.0,...,1111955.0,1188387.0,20095185.0,139394781.0,9782060.0,4732900.0,189688272.0,5087755.0,10595591.0,379376544.0

In [43]:
# Create a new dataframe for those states who have a population of at least five million...
# have at least 500k in Total driving & total Public transit.

states_over_5million = combined_states_df.loc[(combined_states_df["Grand Total"] >= 5000000)]

# Set the index of this new dataframe to be the state's names
states_over_5million = states_over_5million.set_index("state")

#states_over_5million

# Charting transport population...

* Create a variable and an input that asks the user what State they would like to look for.

* Store each individual State's output over time in a variable

* Store that same State's output over time in a variable as well

* Create a line chart that will plot this States's output and output from 2009 to 2019

In [44]:
# Collect the user's input to search through our data frame
state_1 = "Virginia" # input("Type the first state you want to compare? ")
state_2 = "Maryland" #input("Type the first state you want to compare? ")

In [45]:
states_over_5million.tail()

,carpool2009,carpool2010,carpool2011,carpool2012,carpool2013,carpool2014,carpool2015,carpool2016,carpool2017,carpool2018,...,WFH2018,WFH2019,Total Carpool,Total Drove,Total PublicTransit,Total TaxiBikes,Total Transport,Total Walked,Total WFH,Grand Total
state,,,,,,,,,,,,,,,,,,,,,
Virginia,396824.0,383909.0,355426.0,393282.0,376679.0,378398.0,374422.0,393221.0,362924.0,384725.0,...,236778.0,247137.0,4185754.0,34452955.0,1973688.0,738876.0,44575654.0,1066062.0,2158089.0,89151078.0
Washington,350836.0,319376.0,315066.0,340987.0,322660.0,335648.0,330657.0,341795.0,64022.0,357163.0,...,238682.0,242446.0,3448789.0,26476689.0,2303480.0,765593.0,36713295.0,1297391.0,2122451.0,73127688.0
West Virginia,76548.0,68388.0,76693.0,77490.0,79513.0,71268.0,62754.0,67100.0,224352.0,62368.0,...,24893.0,28665.0,932507.0,6603278.0,68250.0,88569.0,8024507.0,232293.0,259940.0,16209344.0
Wisconsin,258073.0,242836.0,246896.0,250241.0,231596.0,234322.0,229662.0,239740.0,28481.0,222219.0,...,142881.0,150833.0,2420607.0,25428814.0,566966.0,518910.0,31520370.0,1002517.0,1386685.0,62844869.0
Wyoming,30076.0,30849.0,31067.0,33043.0,31509.0,32672.0,28959.0,25590.0,73790.0,28889.0,...,17692.0,16007.0,378628.0,2409466.0,45747.0,64317.0,3131940.0,121246.0,157845.0,6309189.0

In [46]:
# Create a series that looks for a State by name and then traces their Carpool population from 2009 to 2019
carpool_over_time1 = states_over_5million.loc[state_1,["carpool2009","carpool2010", "carpool2011", "carpool2012", "carpool2013",
                                                        "carpool2014", "carpool2015", "carpool2016", "carpool2017", "carpool2018", "carpool2019"]]

# Create a series that looks for a State by name and then traces their Public population from 2009 to 2019
publicTransit_over_time1 = states_over_5million.loc[state_1,["public2009","public2010", "public2011", "public2012", "public2013",
                                                       "public2014", "public2015", "public2016", "public2017", "public2018", "public2019"]]


# Create a series that looks for a State by name and then traces their Carpool population from 2009 to 2019
carpool_over_time2 = states_over_5million.loc[state_2,["carpool2009","carpool2010", "carpool2011", "carpool2012", "carpool2013",
                                                        "carpool2014", "carpool2015", "carpool2016", "carpool2017", "carpool2018", "carpool2019"]]

# Create a series that looks for a State by name and then traces their Public population from 2009 to 2019
publicTransit_over_time2 = states_over_5million.loc[state_2,["public2009","public2010", "public2011", "public2012", "public2013",
                                                        "public2014", "public2015", "public2016", "public2017", "public2018", "public2019"]]

In [47]:
# Create a list of the years that we will use as our x axis
years = [2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
plt.figure()
# Plot our line that will be used to track a States's Carpool over the years...
plt.plot(years, publicTransit_over_time1, color="mediumvioletred", linestyle = '--', label=f"{state_1}'s Public")
plt.plot(years, publicTransit_over_time2, color="aqua", linestyle = '--', label=f"{state_2}'s Public")

# Plot our line that will be used to track a State's Driving over the years...
plt.plot(years, carpool_over_time1, color="crimson", label=f"{state_1}'s Carpool")
plt.plot(years, carpool_over_time2, color="blue", label=f"{state_2}'s Carpool")

# Place a legend on the chart in what matplotlib believes to be the "best" location
plt.legend(bbox_to_anchor=(0.5, 0., 0.5, 0.5), loc='center', borderaxespad=0.1)



plt.title(state_1 +  ' '+ 'vs' + ' ' + state_2 + "'s Transport Population") 
plt.xlabel("Years")
plt.xticks(np.arange(min(years), max(years)+1, 1.0))
plt.ylabel("Number of Carpool/Public Transport")

# Print our chart to the screen
plt.show()